#### **autograd包：**对tensor的各种operation进行自动微分    
+ 如何设置自动微分： torch.tensor()具有一个属性.requires_grad，设置为True表明自动微分。
+ 如何禁止自动微分： 对tensor调用.detach()的方法，或者使用with torch.no_grad() 
+ 如何查看微分的值： 在因变量经过.backward()后，可调用该tensor的.grad属性查看其导数的值。  
+ 如果因变量是一个scalar，直接调用.backward()即可；如果不是，调用时需要加一个和因变量一样shape的参数。

#### **Function类：**Funcion和Tensor是相互关联的
+ 每个tensor都有一个参考自Funcion的属性.grad_fn


In [1]:
import torch

# requires_grad是啥？     
# 是构造tensor时的参数，为True表明；为False表明

# .grad_fn是啥？
# 是tensor的属性attribute，

# .backward()是啥？
# 是因变量scalar的方法method()，
# 如果因变量不是scalar，可以使用.backward(v)，其中v是任意和自变量shape相同的tensor

# .grad是啥？
# 是自变量tensor的属性，计算上述scalar对该tensor的导数

# 如果不想对.requires_grad=True的tensor进行autograd，该咋个操作？
# 方法一：用with torch.no_grad()
# 方法二：对上述Tensor调用y = x.detach()方法

In [2]:
x = torch.ones(2, 2, requires_grad = True)    
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [4]:
y.grad_fn

In [5]:
z = y * y * 3
out = z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [6]:
a = torch.randn(2, 2)
a = ((a*3) / (a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)

b = (a * a).sum()
print(b.grad_fn)

False
True


In [7]:
out.backward()

In [8]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [9]:
x = torch.randn(3, requires_grad = True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([ -97.3127, -981.8997,  426.7000], grad_fn=<MulBackward0>)


In [10]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [11]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


In [16]:
x = torch.tensor([1. ,2.], requires_grad=True)
print(x.requires_grad)

y = x.detach()
print(y.requires_grad)

print(x.eq(y).all())

True
False
tensor(True)
