In [1]:
from __future__ import print_function
import torch
print(torch.__version__)

1.3.1


In [9]:
x = torch.empty(5,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [10]:
x = torch.rand(5,3)
print(x)

tensor([[0.8694, 0.0311, 0.8955],
        [0.5981, 0.3908, 0.0991],
        [0.0701, 0.7183, 0.1113],
        [0.4903, 0.0161, 0.4880],
        [0.1990, 0.4084, 0.4323]])


In [12]:
x = torch.zeros(5,3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [14]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [15]:
x = x.new_ones(5, 3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [16]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[-0.1086, -0.1454,  0.6551],
        [-0.6625,  0.0575, -0.8070],
        [-1.8442,  1.3965, -0.4695],
        [ 1.2675,  0.9335, -2.5723],
        [ 0.1145,  0.1755,  0.2386]])

In [21]:
x.size()

torch.Size([5, 3])

In [22]:
y = torch.rand(5,3)
x + y

tensor([[ 0.3865,  0.7327,  1.4300],
        [-0.4912,  0.1917, -0.4299],
        [-0.9371,  2.0024,  0.4571],
        [ 1.5331,  1.8874, -2.1863],
        [ 0.2452,  0.9219,  0.7617]])

In [24]:
torch.add(x, y)

tensor([[ 0.3865,  0.7327,  1.4300],
        [-0.4912,  0.1917, -0.4299],
        [-0.9371,  2.0024,  0.4571],
        [ 1.5331,  1.8874, -2.1863],
        [ 0.2452,  0.9219,  0.7617]])

In [25]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.3865,  0.7327,  1.4300],
        [-0.4912,  0.1917, -0.4299],
        [-0.9371,  2.0024,  0.4571],
        [ 1.5331,  1.8874, -2.1863],
        [ 0.2452,  0.9219,  0.7617]])


In [26]:
y.add_(x)  ### 注意，一个tensor调用带有_后缀的操作，是inplace的，会改变其自身的值
y

tensor([[ 0.3865,  0.7327,  1.4300],
        [-0.4912,  0.1917, -0.4299],
        [-0.9371,  2.0024,  0.4571],
        [ 1.5331,  1.8874, -2.1863],
        [ 0.2452,  0.9219,  0.7617]])

In [28]:
y[:, 1]

tensor([0.7327, 0.1917, 2.0024, 1.8874, 0.9219])

In [30]:
x = torch.randn(4,4)
y = x.view(16)
y.shape

torch.Size([16])

In [31]:
z = x.view(-1, 8)
z

tensor([[-0.4394,  1.7601,  0.2168,  0.0148,  1.7517,  0.5514, -0.1493, -1.1944],
        [ 0.4928, -0.5748,  0.9294,  0.9728,  0.2556,  0.1696, -0.9886,  1.2419]])

In [35]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.1159])
0.11585620045661926


In [36]:
a = torch.ones(5,2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [38]:
b = a.numpy()
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [39]:
a.add_(1)
print(a)
print(b)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])
[[2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]]


In [42]:
import numpy as np
a = np.ones((5,2))
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[[2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]]
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]], dtype=torch.float64)


In [46]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)    # directly create a tensor on GPU
    x = x.to(device)                         # or just use stings ".to("cuda")"
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([1.1159], device='cuda:0')
tensor([1.1159], dtype=torch.float64)
